package dsl

import dsl._

object Test extends MySIMPLDSL {
  
  def main(args: Array[String]) {
    println(p|'x|'x→0|('x≥0)?('x→1,'x→2)|r('x)|GO)
               
    // MySIMPL Test Cases
    Test("[var,x,;,x,<-,0,;,if,'(',x,>=,0,')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(',x,>,0,')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(',x,<,0,')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(',x,<=,0,')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(',x,==,0,')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(',x,!=,0,')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,a,;,var,y,;,var,z,;,var,b,;,a,<-,42,;,y,<-,42,;,if,'(','(',a,+,a,')',==,84,')',then,y,<-,1,;,b,<-,2,'.',else,z,<-,2,;,b,<-,2,'.',endif,;,return,y,'.'] | 1.0")
    Test("[var,a,;,var,y,;,var,z,;,var,b,;,a,<-,42,;,z,<-,0,;,if,'(','(',a,*,a,')',==,84,')',then,y,<-,1,;,b,<-,2,'.',else,z,<-,2,;,b,<-,2,'.',endif,;,return,z,'.'] | 2.0")
    Test("[var,x,;,var,y,;,var,z,;,var,k,;,x,<-,10,;,y,<-,3,;,z,<-,100,;,k,<-,0,;,if,'(',x,>,y,')',then,if,'(',x,>,y,')',then,k,<-,100,'.',else,k,<-,3,'.',endif,'.',else,if,'(',z,<,y,')',then,k,<-,2,'.',else,k,<-,9,'.',endif,'.',endif,;,return,k,'.'] | 100.0")
    Test("[var,x,;,var,y,;,var,z,;,var,k,;,x,<-,2,;,y,<-,3,;,z,<-,100,;,k,<-,0,;,if,'(',x,>,y,')',then,if,'(',x,>,y,')',then,k,<-,100,'.',else,k,<-,3,'.',endif,'.',else,if,'(',z,<,y,')',then,k,<-,2,'.',else,k,<-,9,'.',endif,'.',endif,;,return,k,'.'] | 9.0")
    Test("[var,k,;,k,<-,0,;,if,'(',10,<,20,')',then,k,<-,100,'.',else,k,<-,3,'.',endif,;,return,k,'.'] | 100.0")
    Test("[var,k,;,k,<-,0,;,if,'(',10,>,20,')',then,k,<-,100,'.',else,k,<-,3,'.',endif,;,return,k,'.'] | 3.0")
    Test("[var,x,;,if,'(',0.0,>=,0,')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,if,'(',1.0,==,1,')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,if,'(',1.0,!=,1,')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(',x,>=,0,')',then,x,<-,1,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(',x,>,0,')',then,x,<-,1,'.',endif,;,return,x,'.'] | 0.0")
    Test("[var,x,;,var,y,;,var,z,;,var,k,;,x,<-,10,;,y,<-,3,;,z,<-,100,;,k,<-,0,;,if,'(',x,>,y,')',then,if,'(',x,>,y,')',then,k,<-,100,'.',endif,'.',else,if,'(',z,<,y,')',then,k,<-,2,'.',else,k,<-,9,'.',endif,'.',endif,;,return,k,'.'] | 100.0")
    Test("[var,x,;,x,<-,0,;,while,'(',x,>,0,')',do,x,<-,1,'.',done,;,return,x,'.'] | 0.0")
    Test("[var,x,;,x,<-,0,;,while,'(',x,<=,0,')',do,x,<-,1,'.',done,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,10,;,while,'(',x,>=,5,')',do,x,<-,'(',x,-,1,')','.',done,;,return,x,'.'] | 4.0")
    Test("[var,x,;,x,<-,0,;,while,'(',x,<,4,')',do,x,<-,'(',x,+,1,')','.',done,;,return,x,'.'] | 4.0")
    Test("[var,x,;,x,<-,0,;,while,'(',x,==,4,')',do,x,<-,5,'.',done,;,return,x,'.'] | 0.0")
    Test("[var,x,;,x,<-,0,;,while,'(',x,!=,4,')',do,x,<-,4,'.',done,;,return,x,'.'] | 4.0")
    Test("[var,x,;,x,<-,0,;,var,sum,;,sum,<-,0,;,while,'(',x,<,100,')',do,x,<-,'(',x,+,1,')',;,sum,<-,'(',sum,+,x,')','.',done,;,return,sum,'.'] | 5050.0")
    Test("[var,a,;,var,x,;,var,b,;,var,i,;,var,N,;,a,<-,0,;,b,<-,1,;,N,<-,10,;,i,<-,0,;,while,'(',i,<,N,')',do,x,<-,'(',a,+,b,')',;,a,<-,b,;,b,<-,x,;,i,<-,'(',i,+,1,')','.',done,;,return,b,'.'] | 89.0")
    Test("[var,m,;,var,n,;,var,R,;,m,<-,2,;,n,<-,3,;,R,<-,0,;,while,'(',n,>,0,')',do,m,<-,1,;,while,'(',m,<,n,')',do,R,<-,'(',R,+,m,')',;,m,<-,'(',m,+,1,')','.',done,;,n,<-,'(',n,-,1,')','.',done,;,return,R,'.'] | 4.0")
    Test("[var,x,;,x,<-,0,;,while,'(',!,'(',true,')',')',do,x,<-,1,'.',done,;,return,x,'.'] | 0.0")
    Test("[var,x,;,x,<-,0,;,while,'(','(',true,&&,x,==,0,')',')',do,x,<-,1,'.',done,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,while,'(','(',false,||,x,==,0,')',')',do,x,<-,1,'.',done,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,var,y,;,y,<-,0,;,while,'(','(',y,<=,5,&&,x,==,0,')',')',do,x,<-,1,;,y,<-,'(',y,+,1,')','.',done,;,return,y,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,var,y,;,y,<-,0,;,while,'(','(',y,<=,5,||,x,==,0,')',')',do,x,<-,3,;,y,<-,'(',y,+,1,')','.',done,;,return,'(',x,+,y,')','.'] | 9.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(',1,==,1,&&,1,!=,1,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(',1,==,1,&&,1,==,1,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(',1,!=,1,&&,1,==,1,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(',1,!=,1,&&,1,!=,1,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(',1,==,1,||,1,==,1,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(',1,==,1,||,1,!=,1,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(',1,!=,1,||,1,==,1,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(',1,!=,1,||,1,!=,1,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,while,'(','(',1,==,1,&&,1,!=,1,')',')',do,x,<-,1,'.',done,;,return,x,'.'] | 0.0")
    Test("[var,x,;,x,<-,0,;,if,'(',true,')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(',false,')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(',true,&&,false,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(',false,&&,true,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(',true,||,false,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(',false,||,true,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(',false,||,false,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(',false,&&,false,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(',true,&&,true,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(',true,||,true,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(',!,'(',true,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(',!,'(',false,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(',!,'(','(',true,&&,false,')',')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(',!,'(','(',true,&&,true,')',')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(',!,'(','(',true,||,false,')',')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(',!,'(','(',false,||,false,')',')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(',!,'(',x,>=,0,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(',!,'(',x,>,0,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(',!,'(',x,==,0,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(',!,'(',x,!=,0,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(','(',1,==,1,&&,1,!=,1,')',||,1,!=,1,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(','(',1,==,1,&&,1,==,1,')',||,1,!=,1,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(','(','(',1,==,1,&&,1,!=,1,')',&&,1,==,1,')',&&,1,==,1,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 2.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(','(','(',1,==,1,&&,1,==,1,')',&&,1,==,1,')',&&,1,==,1,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(','(','(',1,==,1,&&,1,==,1,')',||,1,!=,1,')',&&,1,==,1,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[var,x,;,x,<-,0,;,if,'(','(','(','(',1,==,1,&&,1,!=,1,')',||,1,!=,1,')',||,1,==,1,')',')',then,x,<-,1,'.',else,x,<-,2,'.',endif,;,return,x,'.'] | 1.0")
    Test("[function,foo,'(',x,')','{',return,1,'.','}',;,return,0,'.'] | 0.0")
    Test("[function,foo,'(',x,')','{',return,1,'.','}',;,return,foo,'(',0,')','.'] | 1.0")
    Test("[function,foo,'(',x,')','{',return,'(',x,*,x,')','.','}',;,return,foo,'(',5,')','.'] | 25.0")
    Test("[function,foo,'(',x,')','{',var,y,;,y,<-,'(',x,*,x,')',;,return,'(',y,+,y,')','.','}',;,var,y,;,y,<-,1,;,return,foo,'(',10,')','.'] | 200.0")
    Test("[function,foo,'(',x,')','{',var,y,;,y,<-,'(',x,*,x,')',;,return,'(',y,+,y,')','.','}',;,var,x,;,x,<-,10,;,return,foo,'(','(',x,/,2,')',')','.'] | 50.0")
    Test("[var,a,;,a,<-,2,;,function,foo,'(',x,')','{',var,y,;,y,<-,'(',a,*,x,')',;,return,'(',y,+,a,')','.','}',;,var,z,;,z,<-,10,;,return,foo,'(',z,')','.'] | 22.0")
    Test("[function,foo,'(',x,')','{',var,y,;,y,<-,'(',a,*,x,')',;,return,'(',y,+,a,')','.','}',;,var,a,;,a,<-,2,;,var,z,;,z,<-,10,;,return,foo,'(',z,')','.'] | 22.0")
    Test("[function,inc1,'(',x,')','{',x,<-,'(',x,+,1,')',;,return,x,'.','}',;,function,inc2,'(',x,')','{',x,<-,'(',x,+,2,')',;,return,x,'.','}',;,var,x,;,x,<-,10,;,return,inc1,'(',inc2,'(',x,')',')','.'] | 13.0")
    Test("[function,inc1,'(',x,')','{',x,<-,'(',x,+,1,')',;,return,x,'.','}',;,function,inc2,'(',x,')','{',x,<-,'(',x,+,2,')',;,return,x,'.','}',;,function,inc3,'(',x,')','{',x,<-,'(',x,+,3,')',;,return,x,'.','}',;,var,x,;,x,<-,10,;,return,inc1,'(',inc2,'(',inc3,'(',x,')',')',')','.'] | 16.0")
    Test("[function,times2,'(',x,')','{',return,'(',x,*,2,')','.','}',;,function,times3,'(',x,')','{',return,'(',x,*,3,')','.','}',;,function,times6,'(',x,')','{',return,times2,'(',times3,'(',x,')',')','.','}',;,function,times12,'(',x,')','{',return,times6,'(',times2,'(',x,')',')','.','}',;,return,times12,'(',10,')','.'] | 120.0")
  }
  
}